// ============================================================
// BANCO DE PREGUNTAS - Electrónica 1 y Electrónica 2
// Basado en los simulacros y exámenes del Inst. Anacleto Tobar
// ============================================================

const BANCO_E1 = [
  {tipo:"mc",q:"Un resistor con bandas Rojo-Rojo-Marrón-Oro conectado a 9V. ¿Qué potencia disipa y qué pasa si es de 1/4W?",o:["0.37W → se daña (supera 0.25W)","0.08W → sobrevive","0.81W → explota","9W → todo bien"],a:0},
  {tipo:"mc",q:"Necesitás 530Ω pero no existe en serie E12. ¿Qué combinación en serie usás?",o:["470Ω + 56Ω","330Ω + 200Ω","220Ω + 310Ω","500Ω + 30Ω"],a:0},
  {tipo:"mc",q:"Un resistor Rojo-Violeta-Rojo-Oro vale:",o:["2.7kΩ ±5%","270Ω ±5%","27kΩ ±10%","2.7Ω ±5%"],a:0},
  {tipo:"mc",q:"Un resistor Marrón-Negro-Naranja-Oro vale:",o:["10kΩ ±5%","100Ω ±5%","1kΩ ±5%","10Ω ±5%"],a:0},
  {tipo:"mc",q:"Un resistor de 100Ω y 0.25W conectado a 10V:",o:["Disipa 1W → se quema","Disipa 0.1W → sobrevive","Disipa 10W → explota","No se puede calcular"],a:0},
  {tipo:"mc",q:"Un microcontrolador recibe 0.12kV y consume 20mA. Su resistencia equivalente es:",o:["6kΩ","6Ω","600Ω","60Ω"],a:0},
  {tipo:"mc",q:"Dos resistores de 200Ω en paralelo, en serie con 100Ω. La Rt total es:",o:["200Ω","500Ω","300Ω","250Ω"],a:0},
  {tipo:"mc",q:"3 resistores en serie con 12V y 2mA. R1=1kΩ, R3=2kΩ. ¿Cuánto vale R2?",o:["3kΩ","6kΩ","1kΩ","9kΩ"],a:0},
  {tipo:"mc",q:"300Ω en serie con (600Ω // 600Ω), alimentado con 12V. La corriente total es:",o:["20mA","10mA","40mA","6.7mA"],a:0},
  {tipo:"mc",q:"Batería 12V con Rs=0.5Ω, lámpara consume 2A. El voltaje real en la lámpara es:",o:["11V","12V","10V","13V"],a:0},
  {tipo:"mc",q:"Batería 20V con Rs=5Ω y carga de 5Ω. La corriente total es:",o:["2A","4A","1A","10A"],a:0},
  {tipo:"mc",q:"Con Rs=5Ω e I=2A, la potencia perdida (calor) dentro de la batería es:",o:["20W","10W","40W","5W"],a:0},
  {tipo:"mc",q:"3 pilas de 1.5V en serie entregan un voltaje de:",o:["4.5V","1.5V","3V","6V"],a:0},
  {tipo:"mc",q:"3 pilas de 2000mAh en serie. La capacidad total es:",o:["2000mAh (no cambia)","6000mAh","1000mAh","667mAh"],a:0},
  {tipo:"mc",q:"Fuente de 0.5V con diodo de Silicio en serie. ¿Conduce?",o:["No (0.5V < 0.7V de barrera)","Sí, es directa","Sí, pero poco","Se quema"],a:0},
  {tipo:"mc",q:"Cambiamos el diodo Si por Germanio (Vk=0.3V), fuente 0.5V. Ahora:",o:["SÍ conduce (0.5V > 0.3V)","Sigue sin conducir","Explota","Igual que antes"],a:0},
  {tipo:"mc",q:"Circuito 12V + diodo directa + 1kΩ. El voltímetro sobre R marca 0V. ¿Qué pasó?",o:["El diodo está abierto (cortado)","El diodo está en corto","Funciona bien","La fuente murió"],a:0},
  {tipo:"mc",q:"En polarización DIRECTA, la zona de deplexión (muro):",o:["Se achica → conduce","Se agranda → bloquea","Desaparece para siempre","No cambia"],a:0},
  {tipo:"mc",q:"En polarización INVERSA, el muro invisible:",o:["Se agranda → NO conduce","Se achica → conduce","Desaparece","Se quema"],a:0},
  {tipo:"mc",q:"Puente rectificador con 15Vp de entrada. El Vpico real (con peaje de 2 diodos) es:",o:["13.6V (15 − 1.4)","14.3V (15 − 0.7)","15V","12V"],a:0},
  {tipo:"mc",q:"Red de 50Hz. La frecuencia a la salida de un rectificador de MEDIA ONDA es:",o:["50Hz","100Hz","25Hz","0Hz"],a:0},
  {tipo:"mc",q:"Red de 50Hz. La frecuencia a la salida de un PUENTE completo es:",o:["100Hz","50Hz","25Hz","200Hz"],a:0},
  {tipo:"mc",q:"Un transformador entrega 12V RMS. El voltaje de pico (Vp) es:",o:["16.97V (12×√2)","12V","8.49V","24V"],a:0},
  {tipo:"mc",q:"El Vdc a la salida de un puente completo es aproximadamente:",o:["2·Vp/π","Vp/π","Vp","Vp/2"],a:0},
  {tipo:"mc",q:"Divisor: R1=1kΩ en serie con LDR. Con luz el LDR baja a 100Ω. Con 10V, el voltaje en R1 es:",o:["9.09V","0.91V","5V","10V"],a:0},
  {tipo:"mc",q:"Si tapás el LDR (su resistencia sube), el voltaje en R1:",o:["Disminuye","Aumenta","No cambia","Se hace cero"],a:0},
  {tipo:"orden",q:"Ordená las etapas de una fuente de alimentación:",items:["Transformador","Rectificador","Filtro","Regulador"],a:[0,1,2,3]},
  {tipo:"unir",q:"Uní cada componente con su función:",pairs:[["Resistor","Se opone a la corriente"],["Capacitor","Almacena campo eléctrico"],["Inductor","Almacena campo magnético"],["Diodo","Conduce en un solo sentido"]]},
  {tipo:"unir",q:"Uní cada concepto con su valor:",pairs:[["Barrera Silicio","0.7V"],["Barrera Germanio","0.3V"],["Salida puente 50Hz","100Hz"],["Vp de 12Vrms","16.97V"]]},
];

const BANCO_E2 = [
  {tipo:"mc",q:"Transformador 220V/12V RMS con puente de 4 diodos. El Vpico real a la salida es:",o:["15.56V (12×√2 − 1.4)","16.97V (12×√2)","12V","10.6V"],a:0},
  {tipo:"mc",q:"¿Por qué en un puente completo restamos 1.4V y no 0.7V?",o:["Conducen 2 diodos a la vez (2×0.7V)","Porque hay 4 diodos","Por el rizado","Por el transformador"],a:0},
  {tipo:"mc",q:"Carga de 400mA, C=1000μF, frecuencia 100Hz. El rizado Vr (pico a pico) es:",o:["4V","2V","0.4V","40V"],a:0},
  {tipo:"mc",q:"La fórmula del rizado pico a pico es:",o:["Vr = IL/(f·C)","Vr = f·C/IL","Vr = IL·f/C","Vr = C/(IL·f)"],a:0},
  {tipo:"mc",q:"Si Vpico=15.56V y Vr=4V, la tensión mínima (piso) es:",o:["11.56V","15.56V","4V","19.56V"],a:0},
  {tipo:"mc",q:"¿Qué tensión mínima de entrada necesita un regulador 7812 para funcionar?",o:["14V (12V + 2V dropout)","12V exactos","10V","16V"],a:0},
  {tipo:"mc",q:"Vmínima=11.56V y querés usar un 7812 (necesita 14V). ¿Funciona?",o:["No, 11.56V < 14V → falla/ruido","Sí, perfecto","Sí, porque > 12V","No se sabe"],a:0},
  {tipo:"mc",q:"Carga 300mA, rizado deseado 2V, freq 100Hz. ¿Qué capacitor se necesita?",o:["1500μF","150μF","15000μF","15μF"],a:0},
  {tipo:"mc",q:"Si medís Vce=0.2V en un BJT, está en zona de:",o:["Saturación (llave cerrada)","Corte (llave abierta)","Activa (amplifica)","Quemado"],a:0},
  {tipo:"mc",q:"Si medís Vce=12V (igual a Vcc) en un BJT, está en:",o:["Corte (no conduce)","Saturación","Activa","Amplificando"],a:0},
  {tipo:"mc",q:"Un transistor en saturación actúa como:",o:["Llave cerrada","Llave abierta","Amplificador","Regulador"],a:0},
  {tipo:"mc",q:"Par Darlington con β₁=120 y β₂=100. La ganancia total es:",o:["12000","220","12","1200"],a:0},
  {tipo:"mc",q:"β₁=100, β₂=120, entran 0.2mA por la base. La corriente al emisor (Ie) es:",o:["2.4A","0.24A","24mA","12A"],a:0},
  {tipo:"mc",q:"El VBE necesario para que un Darlington conduzca es:",o:["1.4V (dos junturas)","0.7V","0.3V","2.1V"],a:0},
  {tipo:"mc",q:"Medís la base del Darlington a masa: 0.9V. ¿Conduce?",o:["No (0.9V < 1.4V)","Sí (0.9V > 0.7V)","Siempre conduce","Depende"],a:0},
  {tipo:"mc",q:"Medís la base del Darlington a masa: 1.1V. ¿Conduce?",o:["No (1.1V < 1.4V)","Sí (1.1V > 0.7V)","Sí (1.1V > 1V)","No se sabe"],a:0},
  {tipo:"mc",q:"Espejo de corriente con Vcc=15V y R=2.2kΩ. La corriente Io es aprox.:",o:["6.5mA","15mA","2.2mA","0.65mA"],a:0},
  {tipo:"mc",q:"Espejo con Vcc=12V y R=2.2kΩ. La corriente Io es aprox.:",o:["5.1mA","12mA","2.2mA","0.51mA"],a:0},
  {tipo:"mc",q:"Si la R de referencia del espejo se quema (abierta), la corriente Io será:",o:["Cero","Infinita","Vcc/R","No cambia"],a:0},
  {tipo:"mc",q:"¿Para qué se usa el espejo de corriente en el 741?",o:["Como carga activa","Para regular tensión","Para filtrar","Para rectificar"],a:0},
  {tipo:"mc",q:"La corriente en el espejo se calcula como:",o:["Io ≈ (Vcc − 0.7)/R","Io = Vcc·R","Io = R/Vcc","Io = 0.7/R"],a:0},
  {tipo:"mc",q:"¿Qué hace el filtro (capacitor) en una fuente?",o:["Suaviza la señal pulsante","Baja la tensión","Regula la salida","Rectifica"],a:0},
  {tipo:"mc",q:"¿Qué hace el regulador 7812 en una fuente?",o:["Mantiene 12V fijos estables","Filtra el rizado","Baja de 220V","Rectifica"],a:0},
  {tipo:"orden",q:"Ordená las etapas de una fuente completa:",items:["Transformador 220V→12V","Puente de diodos","Filtro capacitor","Regulador 7812"],a:[0,1,2,3]},
  {tipo:"unir",q:"Uní cada concepto con su definición:",pairs:[["βtotal Darlington","β₁ × β₂"],["VBE Darlington","1.4V"],["Io espejo","(Vcc−0.7)/R"],["Dropout 7812","2V mínimo"]]},
  {tipo:"unir",q:"Uní cada zona del transistor:",pairs:[["Corte","Ic=0, llave abierta"],["Activa","Ic=β·Ib, amplifica"],["Saturación","Vce≈0.2V, llave cerrada"]]},
];
